language: cpp

branches:
  only:
    - dev
    - master

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq autoconf automake libtool libboost-python-dev python-numpy && sudo rm -r /opt/python/*; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install boost-python gflags; export CXX=clang++; fi
  - wget http://bitbucket.org/eigen/eigen/get/3.2.4.tar.bz2
  - tar xvjf 3.2.4.tar.bz2
  - cd eigen-eigen-10219c95fe65
  - mkdir build; cd build
  - cmake .. && sudo make install
  - cd ../../
  - rm -rf 3.2.4.tar.gz2 eigen-eigen-10219c95fe65

before_script:
  - ./autogen.sh
  - echo "#define CMAES_EXPORT" > cmaes_export.h
  - if [ $TRAVIS_OS_NAME == linux ]; then ./configure --enable-python; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./configure --enable-python LDFLAGS="-L/usr/local/lib/"; fi

script: make

os: 
 - linux
 - osx
